module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: { '^.+\\.(t|j)s$': ['ts-jest', { tsconfig: '<rootDir>/../tsconfig.json' }] },
  collectCoverageFrom: ['**/*.(t|j)s', '!**/*.spec.ts', '!**/index.ts'],
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/src/main\\.ts$',
    '/src/app\\.module\\.ts$',
    '\\.module\\.ts$',
    '/src/database/',
    '/src/config/database\\.config\\.ts$',
    '/src/config/env\\.validation\\.ts$',
    '/dto/',
  ],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  moduleNameMapper: { '^@/(.*)$': '<rootDir>/$1' },
}
